# Site settings
baseURL = "https://4clansing.org"
languageCode = "en-US"
title = "Connecting. Learning. Growing."
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "RSS", "sitemap"]
disableHugoGeneratorInject = true

# Local preview mode
relativeURLs = true
uglyURLs = true

# Copyright
copyright = "&copy;2025 Cross-Cultural Community Connections"

[services]
  [services.googleAnalytics]
    # Enter your tracking code to enable Google Analytics
    ID = ""

[params]

  # Metadata for search engines and social sharing
  author = "4C Lansing"
  description = "Our mission is to support, encourage, and promote cross-cultural community connections."
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  # Whether you purchased the license from the author.
  licensed = false

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.png"
      position = "center center"

    # Video
    # [params.visual.video]
    #   enable = false
    #   mute = true
    #   file = "videos/background.mp4"
    #   # youtubeId = "dk9uNWPP7EA"

  [params.custom.css]
  enable = true

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:4clansing.org@gmail.com"
        new_tab = false # Default, open at same tab

      [[params.links.list1.link]]
        text = "Facebook"
        url = "https://www.facebook.com/cross.cultural.community.connections"
        new_tab = true # Default, open at same tab


  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Learn"

      [[params.links.list2.link]]
        text = "About"
        url = "#"

      [[params.links.list2.link]]
        text = "Mission"
        url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list3]
      heading = "Grow"

      [[params.links.list3.link]]
        text = "Appointments"
        url = "link_to_form"
        new_tab = true # Default, open at same tab
        
      [[params.links.list3.link]]
        text = "Resources"
        url = "#"
        new_tab = true # Default, open at same tab

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split

[server]
[[server.headers]]
    for = '/**'
    [server.headers.values]
      Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://dummyimage.com"
      Referrer-Policy = 'strict-origin-when-cross-origin'
      X-Content-Type-Options = 'nosniff'
      X-Frame-Options = 'DENY'
      X-XSS-Protection = '1; mode=block'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true